<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Marten.AspNetCore" Version="7.40.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
<!--        <PackageReference Include="WolverineFx" Version="3.12.2" />-->
        <PackageReference Include="WolverineFx.Http" Version="3.12.2" />
<!--        <PackageReference Include="WolverineFx.Http.FluentValidation" Version="3.12.2" />-->
        <PackageReference Include="WolverineFx.Http.Marten" Version="3.12.2" />
        
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MeetingScheduler.Endpoints\MeetingScheduler.Endpoints.csproj" />
      <ProjectReference Include="..\MeetingScheduler.Identity.Endpoints\MeetingScheduler.Identity.Endpoints.csproj" />
    </ItemGroup>

</Project>
