<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="WolverineFx.Http" Version="3.12.2" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\MeetingScheduler.Shared.Application\MeetingScheduler.Shared.Application.csproj" />
    </ItemGroup>

</Project>
